Full/Testing/Controllers/DongGopController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Testing.Models;
using Testing.ViewModels;

namespace Testing.Controllers
{
    public class DongGopController : Controller
    {
        Model1 data = new Model1();
        // GET: DongGop
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DanhSachTruyen()
        {
            List<TruyenDaTao> truyens = new List<TruyenDaTao>();
           
            var listtruyen = data.Truyens.ToList();
             foreach (var truyen in listtruyen)
            {
                TruyenDaTao truyen1 = new TruyenDaTao();
                truyen1.MaProject = truyen.MaProject;
                truyen1.AnhBia = truyen.AnhBia;
                truyen1.TenTruyen = truyen.TenProject;
                truyen1.TacGia = truyen.TacGia;
                truyen1.TrangThai = truyen.TrangThai1.TenTrangThai;
                truyen1.NgayTao = truyen.NgayTao.ToShortDateString();
                 
                truyens.Add(truyen1);
               

            }
            return View(truyens);
        }
       public ActionResult DanhSachChuong(int id)
        {
            DAO.DaoChuongTruyen dao = new DAO.DaoChuongTruyen();
            var list = dao.LayListChuongTruyen(id);
            return View(list);
        }
        [HttpPost]
        public ActionResult Upload(TrangTruyen model, HttpPostedFileBase fileupload)
        {
            var nguoi = (NguoiDung)Session["TaiKhoan"];
            
            var filename = Path.GetFileName(fileupload.FileName);
            var path = Path.Combine(Server.MapPath("~/Truyen"), filename);
            fileupload.SaveAs(path);
            TrangTruyen trang = new TrangTruyen();
            if(model.MaLoaiTrang == 2)
            {
                trang.MaNguoiDung = nguoi.MaNguoiDung;
                trang.MaLoaiTrang = 4;
                trang.TenTrang = model.TenTrang;
                trang.ThuTu = model.ThuTu;
                trang.UrlAnh = filename;
                trang.MaChuongTruyen = model.MaChuongTruyen;
                trang.DaXoa = false;
                data.TrangTruyens.Add(trang);
                
            }
            else
            {
                var trang1 = data.TrangTruyens.SingleOrDefault(m => m.MaTrangTruyen == model.MaTrangTruyen);
                trang1.UrlAnh = filename;
               
            }
            data.SaveChanges();
            return RedirectToAction("UploadCleartext", new { id=model.MaChuongTruyen});

        }
        public ActionResult UploadCleartext(int id)
        {
            
            var list = new List<TrangTruyen>();
            DAO.DaoChuongTruyen dao = new DAO.DaoChuongTruyen();
            list = dao.ListTrangCvaR(id);
            return View(list);
        }
       
    }
}

Full/Testing/Views/DongGop/DanhSachChuong.cshtml
@using Testing.ViewModels
@using PagedList.Mvc;
@model IEnumerable<ChuongTruyenDaTao>
@{
    /**/

    ViewBag.Title = "@ViewBag.TenTruyen";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="padding">
    <div class="m-b">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/User/Index">Home</a></li>
            <li class="breadcrumb-item"><a href="/Truyen/QuanLyTruyenDaTao">Danh sách truyện đã tạo</a></li>
            <li class="breadcrumb-item active">Danh sách chương</li>
        </ol>
    </div>
    <div class="box">
        <div class="box-header">

        </div>
        @using (Html.BeginForm("QuanLyChuong", "Truyen", FormMethod.Post))
        {
            <div class="table-responsive">
                <table ui-jp="dataTable" class="table table-striped b-t b-b">
                    <thead>
                        <tr>
                           
                            <th style="width:30%">Tên Chương</th>
                            <th style="width:15%">Thời gian cập nhật</th>
                            <th style="width:10%">Lượt xem</th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="center">
                                    <a href="/DongGop/UploadCleartext/@item.MaChuong">
                                        <span>
                                            @Html.DisplayFor(modelItem => item.TenChuong)
                                        </span>
                                    </a>
                                </td>
                                <td class="center">
                                    @Html.DisplayFor(modelItem => item.Thoigian)
                                </td>
                                <td class="center">
                                    @Html.DisplayFor(modelItem => item.LuotXem)
                                </td>


                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>

</div>

Full/Testing/Views/DongGop/DanhSachTruyen.cshtml
@using Testing.ViewModels
@model IEnumerable<TruyenDaTao>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    .mr10 {
        margin-right: 20px;
    }
</style>
<div class="padding">
    <div class="m-b">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/User/Index">Index</a></li>
            <li class="breadcrumb-item active">Danh sách truyện</li>
        </ol>
    </div>
    <div class="box">
        <div class="box-header">
            <h2>DataTables</h2>
        </div>
        
            <div class="table-responsive">
                <table ui-jp="dataTable" id="datatable" class="table table-striped b-t b-b">
                    <thead>
                        <tr>
                           
                            <th style="width:10%">Ảnh Bìa</th>
                            <th style="width:25%">Tên Truyện</th>
                            <th style="width:15%">Tác Giả</th>
                            <th style="width:15%">Trạng Thái</th>
                            <th style="width:15%">Ngày Tạo</th>
                           
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="center">
                                    <a href="/DongGop/DanhSachChuong/@item.MaProject">
                                        <span>
                                            <img src="~/Truyen/@item.AnhBia" style="width:140px; height:120px;" />
                                        </span>
                                    </a>

                                </td>
                                <td class="center">
                                    <a href="/Truyen/QuanLyChuong/@item.MaProject">
                                        <span>
                                            @Html.DisplayFor(modelItem => item.TenTruyen)
                                        </span>
                                    </a>
                                </td>
                                <td class="center">
                                    @Html.DisplayFor(modelItem => item.TacGia)
                                </td>
                                <td class="center">
                                    @Html.DisplayFor(modelItem => item.TrangThai)
                                </td>
                                <td class="center">
                                    @Html.DisplayFor(modelItem => item.NgayTao)
                                </td>
                                
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        
    </div>

</div>

Full/Testing/Views/DongGop/Upload.cshtml
@model Testing.Models.TrangTruyen
<div class="col-xs-6 col-sm-4 col-md-3">
    <div class="box p-a-xs" >
        @using (Html.BeginForm("Upload", "DongGop", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
           
           <input type="hidden" name="MaChuongTruyen" id="MaChuongTruyen" value="@Model.MaChuongTruyen" />
           <input type="hidden" name="ThuTu" id="ThuTu" value="@Model.ThuTu" />
           <input type="hidden" name="MaLoaiTrang" id="MaLoaiTrang" value="@Model.MaLoaiTrang" />
           <input type="hidden" name="MaTrangTruyen" id="MaTrangTruyen" value="@Model.MaTrangTruyen" />
            <input type="hidden" name="TenTrang" id="TenTrang" value="@Model.TenTrang" />
            @Html.AntiForgeryToken()
            <a href="#"><img src="~/Truyen/@Model.UrlAnh" alt="" class="img-responsive" style="height:304px"></a>
            <div class="p-a-sm" >
                <div class="text-ellipsis">trang @Model.ThuTu</div>
                <div class="row text-center">

                    <input style="margin-left:10px" type="file" id="@Model.TenTrang" name="fileupload" onchange="myFunction23('@Model.TenTrang','@Model.ThuTu')" />
                    @if (@Model.MaLoaiTrang == 4)
                    {
                    <div class="text-ellipsis">
                        <span style="margin-left:10px">Trang này là bản clear-text</span> 
                    </div>
                        <div><button disabled id="@Model.ThuTu" type="submit" class="md-btn md-raised m-b-sm w-xs black" style="margin-top:10px;margin-bottom:2px" onclick="return confirm('Chắc chưa?')">Lưu</button></div>
                        }
                        else
                        {
                        <div style="margin-left:10px"><button disabled id="@Model.ThuTu" type="submit" class="md-btn md-raised m-b-sm w-xs black" style="margin-top:10px;margin-bottom:2px">Lưu</button></div>
                        }

                    </div>
            </div>
        }

    </div>
</div>

Full/Testing/Views/DongGop/UploadCleartext.cshtml
@model IEnumerable<Testing.Models.TrangTruyen>
@{
    ViewBag.Title = "UploadCleartext";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="padding">
    <div class="m-b">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/User/Index">Home</a></li>
            <li class="breadcrumb-item"><a href="/DongGop/DanhSachTruyen">Danh sách truyện</a></li>

            <li class="breadcrumb-item active">Thêm bản clear-text</li>
        </ol>
    </div>
    <div class="col-md-12">
        

            <div class="row">

                @foreach (var item in Model)
                {
                    @Html.Partial("Upload", item)
                }


            </div>
      


    </div>
</div>
<script>
    function myFunction23(a, b) {

        var x = document.getElementById(a);

        if ('files' in x) {
            if (x.files.length == 0) {
                document.getElementById(b).disabled = true;
            } else {
                document.getElementById(b).disabled = false;
            }
        }
    }
</script>